name: demo github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Install SSH keys
        run: |
          #echo "rajan" > ~/.ssh/id_rsa 
          echo ---- take clone in remote server -----
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
      - name: connect and clone
        run: | 
          ssh "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}" << EOF
          #echo ----- make directory in remote server -----
          mkdir new
          #install -m 600 -D /dev/null ~/.ssh/id_rsa
          #echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          #ssh-keyscan -H "${{ secrets.SSH_HOST }}" > ~/.ssh/known_hosts
          #echo ---- take clone in remote server -----
          git clone git@github.com:rajan-addweb/clone-test.git
          exit
          EOF
          #- name: rsync a file in remote server
          #run: rsync -avz ./add "${{ secrets.SSH_USER }}"@"${{ secrets.SSH_HOST }}":/home/ubuntu/new
          #- name: cleanup
          #run: | 
          #rm -rf ~/.ssh
